org: groros
app: pay-per-lead-project
service: stripe-checkout-session-handler

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  environments:
    - STRIPE_API_KEY: ${param:STRIPE_API_KEY}
    - STRIPE_TEST_API_KEY: ${param:STRIPE_TEST_API_KEY}
    - STAGE: ${opt:stage}
    - STRIPE_TEST_LOCAL_SECRET: ${param:STRIPE_TEST_LOCAL_SECRET}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
